/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth.accept-invite'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRecurringTasksRouteImport } from './routes/_app.recurring-tasks'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppTasksIndexRouteImport } from './routes/_app.tasks.index'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppRecurringTasksIndexRouteImport } from './routes/_app.recurring-tasks.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppAssetsIndexRouteImport } from './routes/_app.assets.index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app.users.$userId'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app.tasks.$taskId'
import { Route as AppRecurringTasksScheduleIdRouteImport } from './routes/_app.recurring-tasks.$scheduleId'
import { Route as AppInventoryItemIdRouteImport } from './routes/_app.inventory.$itemId'
import { Route as AppAssetsAssetIdRouteImport } from './routes/_app.assets.$assetId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringTasksRoute = AppRecurringTasksRouteImport.update({
  id: '/recurring-tasks',
  path: '/recurring-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppRecurringTasksIndexRoute = AppRecurringTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRecurringTasksRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppRecurringTasksScheduleIdRoute =
  AppRecurringTasksScheduleIdRouteImport.update({
    id: '/$scheduleId',
    path: '/$scheduleId',
    getParentRoute: () => AppRecurringTasksRoute,
  } as any)
const AppInventoryItemIdRoute = AppInventoryItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppAssetsAssetIdRoute = AppAssetsAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => AppAssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AppAssetsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/recurring-tasks': typeof AppRecurringTasksRouteWithChildren
  '/reports': typeof AppReportsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/users': typeof AppUsersRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/recurring-tasks/$scheduleId': typeof AppRecurringTasksScheduleIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/recurring-tasks/': typeof AppRecurringTasksIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/recurring-tasks/$scheduleId': typeof AppRecurringTasksScheduleIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/assets': typeof AppAssetsIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/recurring-tasks': typeof AppRecurringTasksIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/assets': typeof AppAssetsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/recurring-tasks': typeof AppRecurringTasksRouteWithChildren
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/_app/users': typeof AppUsersRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/_app/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/_app/inventory/$itemId': typeof AppInventoryItemIdRoute
  '/_app/recurring-tasks/$scheduleId': typeof AppRecurringTasksScheduleIdRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/recurring-tasks/': typeof AppRecurringTasksIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/inventory'
    | '/notifications'
    | '/recurring-tasks'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/auth/accept-invite'
    | '/assets/$assetId'
    | '/inventory/$itemId'
    | '/recurring-tasks/$scheduleId'
    | '/tasks/$taskId'
    | '/users/$userId'
    | '/assets/'
    | '/inventory/'
    | '/recurring-tasks/'
    | '/reports/'
    | '/tasks/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/auth/accept-invite'
    | '/assets/$assetId'
    | '/inventory/$itemId'
    | '/recurring-tasks/$scheduleId'
    | '/tasks/$taskId'
    | '/users/$userId'
    | '/assets'
    | '/inventory'
    | '/recurring-tasks'
    | '/reports'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/assets'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/notifications'
    | '/_app/recurring-tasks'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/users'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/auth/accept-invite'
    | '/_app/assets/$assetId'
    | '/_app/inventory/$itemId'
    | '/_app/recurring-tasks/$scheduleId'
    | '/_app/tasks/$taskId'
    | '/_app/users/$userId'
    | '/_app/assets/'
    | '/_app/inventory/'
    | '/_app/recurring-tasks/'
    | '/_app/reports/'
    | '/_app/tasks/'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring-tasks': {
      id: '/_app/recurring-tasks'
      path: '/recurring-tasks'
      fullPath: '/recurring-tasks'
      preLoaderRoute: typeof AppRecurringTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/recurring-tasks/': {
      id: '/_app/recurring-tasks/'
      path: '/'
      fullPath: '/recurring-tasks/'
      preLoaderRoute: typeof AppRecurringTasksIndexRouteImport
      parentRoute: typeof AppRecurringTasksRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/recurring-tasks/$scheduleId': {
      id: '/_app/recurring-tasks/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/recurring-tasks/$scheduleId'
      preLoaderRoute: typeof AppRecurringTasksScheduleIdRouteImport
      parentRoute: typeof AppRecurringTasksRoute
    }
    '/_app/inventory/$itemId': {
      id: '/_app/inventory/$itemId'
      path: '/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof AppInventoryItemIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/assets/$assetId': {
      id: '/_app/assets/$assetId'
      path: '/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AppAssetsAssetIdRouteImport
      parentRoute: typeof AppAssetsRoute
    }
  }
}

interface AppAssetsRouteChildren {
  AppAssetsAssetIdRoute: typeof AppAssetsAssetIdRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
}

const AppAssetsRouteChildren: AppAssetsRouteChildren = {
  AppAssetsAssetIdRoute: AppAssetsAssetIdRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
}

const AppAssetsRouteWithChildren = AppAssetsRoute._addFileChildren(
  AppAssetsRouteChildren,
)

interface AppInventoryRouteChildren {
  AppInventoryItemIdRoute: typeof AppInventoryItemIdRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryItemIdRoute: AppInventoryItemIdRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppRecurringTasksRouteChildren {
  AppRecurringTasksScheduleIdRoute: typeof AppRecurringTasksScheduleIdRoute
  AppRecurringTasksIndexRoute: typeof AppRecurringTasksIndexRoute
}

const AppRecurringTasksRouteChildren: AppRecurringTasksRouteChildren = {
  AppRecurringTasksScheduleIdRoute: AppRecurringTasksScheduleIdRoute,
  AppRecurringTasksIndexRoute: AppRecurringTasksIndexRoute,
}

const AppRecurringTasksRouteWithChildren =
  AppRecurringTasksRoute._addFileChildren(AppRecurringTasksRouteChildren)

interface AppReportsRouteChildren {
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRecurringTasksRoute: typeof AppRecurringTasksRouteWithChildren
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppUsersRoute: typeof AppUsersRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRecurringTasksRoute: AppRecurringTasksRouteWithChildren,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppUsersRoute: AppUsersRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
