/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new user account. New accounts always receive the TECHNICIAN role — role assignment requires an ADMIN via PATCH /users/:id/roles. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterInput"];
                };
            };
            responses: {
                /** @description User created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Email or username already in use */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Too many attempts — rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Authenticate with email and password. Returns an access token in the response body and sets a refresh token as an HttpOnly cookie. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Too many attempts — rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Rotates the refresh token. Reads the refresh token from the HttpOnly cookie, issues a new access token + refresh token pair. If the incoming token was already used (reuse detected), all sessions for the user are revoked. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token refreshed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Missing, invalid, expired, or reused refresh token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Clears the refresh token cookie and removes the session from Redis. Always returns 204, even if no valid session exists. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/accept-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Accept an invite and create your account. The invite token (from the email link) pre-assigns your role. Supply your chosen username and password. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AcceptInviteInput"];
                };
            };
            responses: {
                /** @description Account created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterResponse"];
                    };
                };
                /** @description Invite expired or already used */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invite not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Username already taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return the complete list of valid inventory category values. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of category enum values */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryCategoriesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Aggregate inventory counts grouped by category. Returns totals for inStock, lowStock, and outOfStock across all categories and per category. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Inventory stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryStatsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List inventory items. Supports pagination, search, sorting, `category` filter, and `status` filter (`IN_STOCK`, `LOW_STOCK`, `OUT_OF_STOCK`). */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sortBy?: "name" | "quantity" | "category" | "createdAt";
                    sortOrder?: "asc" | "desc";
                    search?: string;
                    category?: "ELECTRICAL" | "PLUMBING" | "HVAC" | "TOOLS" | "FASTENERS" | "CHEMICALS" | "SAFETY" | "BUILDING_MATERIALS";
                    status?: "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of inventory items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** @description Create a new inventory item. Requires ADMIN or MANAGER role. Serial number must be unique. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateInventoryItemInput"];
                };
            };
            responses: {
                /** @description Item created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryItemResponse"];
                    };
                };
                /** @description Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Serial number already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single inventory item by ID. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Item found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryItemResponse"];
                    };
                };
                /** @description Item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete an inventory item. ADMIN only. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Item deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ADMIN role required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update an inventory item. Requires ADMIN or MANAGER role. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateInventoryItemInput"];
                };
            };
            responses: {
                /** @description Item updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryItemResponse"];
                    };
                };
                /** @description Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/inventory/{id}/restock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Increment an inventory item's quantity by the given amount. Requires ADMIN or MANAGER role. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RestockInventoryItemInput"];
                };
            };
            responses: {
                /** @description Item restocked — updated item returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryItemResponse"];
                    };
                };
                /** @description Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List the authenticated user's notifications. Filterable by `isRead` and `type` (`LOW_STOCK`, `OUT_OF_STOCK`, `TASK_OVERDUE`), always sorted newest first. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    isRead?: string;
                    type?: "LOW_STOCK" | "OUT_OF_STOCK" | "TASK_OVERDUE";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of notifications */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationsListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the count of unread notifications for the authenticated user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unread count */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnreadCountResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Mark all of the authenticated user's unread notifications as read. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notifications marked as read */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarkAllReadResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a notification. Users may only delete their own notifications. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not your notification */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Notification not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Mark a single notification as read or unread. Users may only update their own notifications. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateNotificationInput"];
                };
            };
            responses: {
                /** @description Notification updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationResponse"];
                    };
                };
                /** @description Not your notification */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Notification not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List tasks. Supports search (title + description), `status`, `assignedTo`, `overdue=true`, and `dueDateFrom`/`dueDateTo` date range filters. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sortBy?: "createdAt" | "status" | "title";
                    sortOrder?: "asc" | "desc";
                    search?: string;
                    status?: "OPEN" | "IN_PROGRESS" | "DONE" | "CANCELLED";
                    assignedTo?: string;
                    overdue?: string;
                    dueDateFrom?: string | null;
                    dueDateTo?: string | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TasksListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** @description Create a new task. Requires ADMIN or MANAGER role. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateTaskInput"];
                };
            };
            responses: {
                /** @description Task created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
                /** @description Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single task by ID. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a task. ADMIN only. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ADMIN role required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update a task. ADMIN/MANAGER may update any field. TECHNICIAN may only update `status` on tasks assigned to them. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskInput"];
                };
            };
            responses: {
                /** @description Task updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
                /** @description Technician attempting to update a task not assigned to them, or sending fields other than status */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mark a task as COMPLETED. Requires after photo uploaded, all checklist items checked, and adequate inventory for parts used. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CompleteTaskInput"];
                };
            };
            responses: {
                /** @description Task completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
                /** @description Completion gates not met (missing after photo, unchecked items, insufficient inventory) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/before-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Upload a before photo for a task. Only allowed when task status is IN_PROGRESS. Accepts multipart/form-data with a `photo` field (JPEG, PNG, or WebP; max 5 MB). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Photo uploaded — returns the updated task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
                /** @description Task not in IN_PROGRESS status */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/after-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Upload an after photo for a task. Accepts multipart/form-data with a `photo` field (JPEG, PNG, or WebP; max 5 MB). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Photo uploaded — returns the updated task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/checklist-templates/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the checklist template for a given task category. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    category: "ELECTRICAL" | "PLUMBING" | "HVAC" | "TOOLS" | "FASTENERS" | "CHEMICALS" | "SAFETY" | "BUILDING_MATERIALS";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Checklist template */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChecklistTemplateResponse"];
                    };
                };
                /** @description Category not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all users. Requires ADMIN or MANAGER role. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    role?: "ADMIN" | "MANAGER" | "TECHNICIAN";
                    status?: "ACTIVE" | "INACTIVE";
                    sortBy?: "createdAt" | "userName" | "email";
                    sortOrder?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsersListResponse"];
                    };
                };
                /** @description Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the currently authenticated user's profile. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Own profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single user by ID. Requires ADMIN or MANAGER role. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a user. ADMIN only. An admin cannot delete their own account. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ADMIN role required, or attempting to delete own account */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update a user's profile. A user may update their own profile; ADMINs may update any profile. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserInput"];
                };
            };
            responses: {
                /** @description User updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Not your profile and not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Email or username already in use */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Assign roles to a user. ADMIN only. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateRolesInput"];
                };
            };
            responses: {
                /** @description Roles updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description ADMIN role required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send an invite email to a new user. ADMIN only. The recipient receives a link to set their username and password. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InviteUserInput"];
                };
            };
            responses: {
                /** @description Invite created and email sent */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InviteResponse"];
                    };
                };
                /** @description ADMIN role required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/pending-invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List invites that have been sent but not yet accepted. ADMIN only. Includes an `isExpired` flag for invites past their 48-hour window. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of pending invites */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PendingInvitesResponse"];
                    };
                };
                /** @description ADMIN role required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/invites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Cancel a pending invite that has not yet been accepted. ADMIN only. Returns 400 if the invite was already accepted. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invite cancelled */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invite already accepted */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description ADMIN role required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invite not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Upload or replace the authenticated user's profile picture. Accepts multipart/form-data with an `avatar` field (JPEG, PNG, or WebP; max 5 MB). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Avatar uploaded — returns the updated user profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description No file provided, wrong format, or file too large */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Activate or deactivate a user account. ADMIN only. An admin cannot change their own status. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserStatusInput"];
                };
            };
            responses: {
                /** @description Status updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description ADMIN role required, or attempting to change own status */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /** Format: uuid */
                id: string;
                userName: string;
                email: string;
            };
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @example VALIDATION_ERROR */
                code: string;
                /** @example Validation failed */
                message: string;
                fields?: {
                    [key: string]: string[];
                };
            };
        };
        RegisterInput: {
            /** @example johndoe */
            userName: string;
            /**
             * Format: email
             * @example john@example.com
             */
            email: string;
            /** @example Password123 */
            password: string;
        };
        LoginResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /** @example eyJhbGciOiJIUzI1NiIs... */
                accessToken: string;
                roles: ("ADMIN" | "MANAGER" | "TECHNICIAN")[];
            };
        };
        LoginInput: {
            /**
             * Format: email
             * @example john@example.com
             */
            email: string;
            /** @example Password123 */
            password: string;
        };
        AcceptInviteInput: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            token: string;
            /** @example janedoe */
            userName: string;
            /** @example Password123 */
            password: string;
        };
        InventoryCategoriesResponse: {
            /** @enum {boolean} */
            success: true;
            data: ("ELECTRICAL" | "PLUMBING" | "HVAC" | "TOOLS" | "FASTENERS" | "CHEMICALS" | "SAFETY" | "BUILDING_MATERIALS")[];
        };
        InventoryStatsResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                total: number;
                inStock: number;
                lowStock: number;
                outOfStock: number;
                byCategory: {
                    ELECTRICAL?: {
                        total: number;
                        inStock: number;
                        lowStock: number;
                        outOfStock: number;
                    };
                    PLUMBING?: {
                        total: number;
                        inStock: number;
                        lowStock: number;
                        outOfStock: number;
                    };
                    HVAC?: {
                        total: number;
                        inStock: number;
                        lowStock: number;
                        outOfStock: number;
                    };
                    TOOLS?: {
                        total: number;
                        inStock: number;
                        lowStock: number;
                        outOfStock: number;
                    };
                    FASTENERS?: {
                        total: number;
                        inStock: number;
                        lowStock: number;
                        outOfStock: number;
                    };
                    CHEMICALS?: {
                        total: number;
                        inStock: number;
                        lowStock: number;
                        outOfStock: number;
                    };
                    SAFETY?: {
                        total: number;
                        inStock: number;
                        lowStock: number;
                        outOfStock: number;
                    };
                    BUILDING_MATERIALS?: {
                        total: number;
                        inStock: number;
                        lowStock: number;
                        outOfStock: number;
                    };
                };
            };
        };
        InventoryListResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["InventoryItem"][];
            meta: {
                total: number;
                page: number;
                limit: number;
                pages: number;
            };
        };
        InventoryItem: {
            /** Format: uuid */
            id: string;
            name: string;
            serialNumber: string;
            /** @enum {string} */
            category: "ELECTRICAL" | "PLUMBING" | "HVAC" | "TOOLS" | "FASTENERS" | "CHEMICALS" | "SAFETY" | "BUILDING_MATERIALS";
            quantity: number;
            minStockLevel: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        InventoryItemResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["InventoryItem"];
        };
        CreateInventoryItemInput: {
            /** @example Cordless Drill */
            name: string;
            /** @example SN-00123 */
            serialNumber: string;
            /** @enum {string} */
            category: "ELECTRICAL" | "PLUMBING" | "HVAC" | "TOOLS" | "FASTENERS" | "CHEMICALS" | "SAFETY" | "BUILDING_MATERIALS";
            /** @example 12 */
            quantity: number | null;
            /** @example 5 */
            minStockLevel: number | null;
        };
        RestockInventoryItemInput: {
            /** @example 50 */
            quantityToAdd: number;
        };
        UpdateInventoryItemInput: {
            /** @example Cordless Drill (18V) */
            name?: string;
            /** @enum {string} */
            category?: "ELECTRICAL" | "PLUMBING" | "HVAC" | "TOOLS" | "FASTENERS" | "CHEMICALS" | "SAFETY" | "BUILDING_MATERIALS";
            /** @example 8 */
            quantity?: number | null;
            /** @example 5 */
            minStockLevel?: number | null;
        };
        NotificationsListResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["Notification"][];
            meta: {
                total: number;
                page: number;
                limit: number;
                pages: number;
            };
        };
        Notification: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "LOW_STOCK" | "OUT_OF_STOCK" | "TASK_OVERDUE";
            /** @example Low stock: "Cordless Drill" has 2 units (min: 5). */
            message: string;
            isRead: boolean;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            relatedEntityId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UnreadCountResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /** @example 3 */
                count: number;
            };
        };
        MarkAllReadResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /** @example 5 */
                updated: number;
            };
        };
        NotificationResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["Notification"];
        };
        UpdateNotificationInput: {
            /** @example true */
            isRead: boolean;
        };
        TasksListResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["Task"][];
            meta: {
                total: number;
                page: number;
                limit: number;
                pages: number;
            };
        };
        TaskPartUsage: {
            /** Format: uuid */
            inventoryItemId: string;
            inventoryItem?: {
                /** Format: uuid */
                id: string;
                name: string;
            };
            quantityUsed: number;
        };
        ChecklistItem: {
            item: string;
            checked: boolean;
        };
        ChecklistTemplate: {
            /** @enum {string} */
            category: "ELECTRICAL" | "PLUMBING" | "HVAC" | "TOOLS" | "FASTENERS" | "CHEMICALS" | "SAFETY" | "BUILDING_MATERIALS";
            items: string[];
        };
        ChecklistTemplateResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["ChecklistTemplate"];
        };
        CompleteTaskInput: {
            checklist: string[];
            partsUsed: {
                /** Format: uuid */
                inventoryItemId: string;
                quantity: number;
            }[];
        };
        Task: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            /** @enum {string} */
            status: "OPEN" | "IN_PROGRESS" | "DONE" | "CANCELLED";
            /** @enum {string} */
            priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** @enum {string} */
            category: "ELECTRICAL" | "PLUMBING" | "HVAC" | "TOOLS" | "FASTENERS" | "CHEMICALS" | "SAFETY" | "BUILDING_MATERIALS" | null;
            beforePhotoUrl: string | null;
            afterPhotoUrl: string | null;
            partsUsed: components["schemas"]["TaskPartUsage"][];
            /** Format: uuid */
            assignedTo: string | null;
            assignee: {
                /** Format: uuid */
                id: string;
                userName: string;
                email: string;
            } | null;
            /** Format: date-time */
            dueDate: string | null;
            cancellationReason: string | null;
            /** Format: date-time */
            cancelledAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CancelTaskInput: {
            reason: string;
        };
        TaskResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["Task"];
        };
        CreateTaskInput: {
            /** @example Replace HVAC filter — Building A */
            title: string;
            /** @example Filter is overdue for replacement. */
            description?: string;
            /**
             * Format: uuid
             * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
             */
            assignedTo?: string;
            /**
             * Format: date-time
             * @example 2026-07-01T00:00:00.000Z
             */
            dueDate?: string | null;
            /** @enum {string} */
            priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** @enum {string} */
            category?: "ELECTRICAL" | "PLUMBING" | "HVAC" | "TOOLS" | "FASTENERS" | "CHEMICALS" | "SAFETY" | "BUILDING_MATERIALS";
        };
        UpdateTaskInput: {
            title?: string;
            description?: string;
            /**
             * @example IN_PROGRESS
             * @enum {string}
             */
            status?: "OPEN" | "IN_PROGRESS";
            /** Format: uuid */
            assignedTo?: string | null;
            /** Format: date-time */
            dueDate?: string | null;
            /** @enum {string} */
            priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** @enum {string} */
            category?: "ELECTRICAL" | "PLUMBING" | "HVAC" | "TOOLS" | "FASTENERS" | "CHEMICALS" | "SAFETY" | "BUILDING_MATERIALS";
        };
        UsersListResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["User"][];
            meta: {
                total: number;
                page: number;
                limit: number;
                pages: number;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** @example johndoe */
            userName: string;
            /** @example john@example.com */
            email: string;
            roles: ("ADMIN" | "MANAGER" | "TECHNICIAN")[];
            /**
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /** @enum {string} */
            availability: "AVAILABLE" | "RESERVED" | "BUSY" | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["User"];
        };
        UpdateUserInput: {
            /** @example johndoe2 */
            userName?: string;
            /**
             * Format: email
             * @example newemail@example.com
             */
            email?: string;
        };
        UpdateRolesInput: {
            /**
             * @example [
             *       "MANAGER"
             *     ]
             */
            roles: ("ADMIN" | "MANAGER" | "TECHNICIAN")[];
        };
        InviteResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /** Format: uuid */
                id: string;
                email: string;
                /** @enum {string} */
                role: "MANAGER" | "TECHNICIAN";
                /** Format: date-time */
                expiresAt: string;
            };
        };
        InviteUserInput: {
            /**
             * Format: email
             * @example jane@example.com
             */
            email: string;
            /**
             * @example TECHNICIAN
             * @enum {string}
             */
            role: "MANAGER" | "TECHNICIAN";
        };
        PendingInvitesResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PendingInvite"][];
        };
        PendingInvite: {
            /** Format: uuid */
            id: string;
            email: string;
            /** @enum {string} */
            role: "ADMIN" | "MANAGER" | "TECHNICIAN";
            /** Format: date-time */
            expiresAt: string;
            isExpired: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateUserStatusInput: {
            /**
             * @example INACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
